[package]
name = "tendermint-abci"
version = "0.1.0"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = []
echo-app = []
kvstore-app = []

[dependencies]
bytes = "1.0"
eyre = "0.6"
log = "0.4"
prost = "0.7"
tendermint-proto = { version = "0.17.1", path = "../proto" }
thiserror = "1.0"
