[package]
name = "tendermint-abci"
version = "0.1.0"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"
description = """
    tendermint-abci provides a simple framework with which to build low-level
    applications on top of Tendermint.
    """

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kvstore-rs"
path = "src/application/kvstore/main.rs"
required-features = [ "binary", "kvstore-app" ]

[features]
client = []
echo-app = []
kvstore-app = []
binary = [ "simple_logger", "structopt" ]

[dependencies]
bytes = "1.0"
eyre = "0.6"
log = "0.4"
prost = "0.7"
tendermint-proto = { version = "0.18.0", path = "../proto" }
thiserror = "1.0"

simple_logger = { version = "1.11", optional = true }
structopt = { version = "0.3", optional = true }
