[package]
name = "tendermint-light-client"
version = "0.15.0"
authors = ["Romain Ruetschi <romain@informal.systems>"]
edition = "2018"
license = "Apache-2.0"
readme     = "README.md"
keywords   = ["blockchain", "bft", "consensus", "cosmos", "tendermint"]
repository = "https://github.com/informalsystems/tendermint-rs"

description = """
    Implementation of the Tendermint Light Client Verification Protocol.
"""

[dependencies]
tendermint = { version = "0.15.0", path = "../tendermint" }
tendermint-rpc = { version = "0.15.0", path = "../rpc", features = ["client"] }

anomaly = { version = "0.2.0", features = ["serializer"] }
contracts = "0.4.0"
crossbeam-channel = "0.4.2"
derive_more = "0.99.5"
futures = "0.3.4"
prost-amino = "0.6.0"
serde = "1.0.106"
serde_cbor = "0.11.1"
serde_derive = "1.0.106"
sled = "0.33.0"
static_assertions = "1.1.0"
thiserror = "1.0.15"
tokio = "0.2.20"

[dev-dependencies]
serde_json = "1.0.51"
gumdrop = "0.8.0"

[features]
secp256k1 = ["tendermint/secp256k1", "tendermint-rpc/secp256k1"]
