[workspace]

members = [
    "light-client",
    "light-node",
    "p2p",
    "proto",
    "rpc",
    "rpc-probe",
    "tendermint",
    "testgen",
    "wasm-client",
]

exclude = [
    "proto-compiler"
]
