[workspace]

members = [
    "abci",
    "light-client",
    "light-client-js",
    "p2p",
    "pbt-gen",
    "proto",
    "rpc",
    "tendermint",
    "test",
    "testgen"
]

exclude = [
    "proto-compiler"
]

[patch.crates-io]
flex-error = { git = "https://github.com/informalsystems/flex-error", rev = "97cc1ce7fa798c9c30813bae718c52f4140cd003" }
