[workspace]

members = [
    "abci",
    "light-client",
    "light-client-js",
    "p2p",
    "pbt-gen",
    "proto",
    "rpc",
    "std-ext",
    "tendermint",
    "test",
    "testgen"
]

exclude = [
    "proto-compiler"
]

[profile.release.package.tendermint-light-client-js]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
prost = { git = "https://github.com/tokio-rs/prost", rev = "859f2438d955f8613bb7ca37c83bc990f55d6658" }
