[package]
name       = "tendermint-rpc"
version    = "0.17.0-rc3"
edition    = "2018"
license    = "Apache-2.0"
homepage   = "https://www.tendermint.com/"
repository = "https://github.com/informalsystems/tendermint-rs"
readme     = "README.md"
authors    = [
  "Sean Braithwaite <sean@informal.systems>",
  "Ethan Buchman <ethan@coinculture.info>",
  "Ismail Khoffi <Ismail.Khoffi@gmail.com>",
  "Romain Ruetschi <romain@informal.systems>",
  "Alexander Simmerl <a.simmerl@gmail.com>",
]

description = """
    tendermint-rpc contains the core types returned by a Tendermint node's RPC endpoint.
    All networking related features are feature guarded to keep the dependencies small in
    cases where only the core types are needed.
    """

[package.metadata.docs.rs]
all-features = true

[features]
default = []
http-client = [ "async-trait", "futures", "http", "hyper", "tokio/fs", "tokio/macros" ]
secp256k1 = [ "tendermint/secp256k1" ]
websocket-client = [
  "async-trait",
  "async-tungstenite",
  "futures",
  "tokio/rt",
  "tokio/rt-multi-thread",
  "tokio/fs",
  "tokio/macros",
  "tokio/stream",
  "tokio/sync",
  "tokio/time",
  "tracing"
]

[dependencies]
bytes = "0.5"
chrono = "0.4"
getrandom = "0.1"
serde = { version = "1", features = [ "derive" ] }
serde_bytes = "0.11"
serde_json = "1"
tendermint = { version = "0.17.0-rc3", path = "../tendermint" }
tendermint-proto = { version = "0.17.0-rc3", path = "../proto" }
thiserror = "1"
uuid = { version = "0.8", default-features = false }
subtle-encoding = { version = "0.5", features = ["bech32-preview"] }

async-trait = { version = "0.1", optional = true }
async-tungstenite = { version = "0.10", features = ["tokio-runtime"], optional = true }
futures = { version = "0.3", optional = true }
http = { version = "0.2", optional = true }
tokio = { version = "0.3", optional = true }
tracing = { version = "0.1", optional = true }
pin-project = "1.0.1"

[dependencies.hyper]
version = "0.14.0-dev"
git = "https://github.com/hyperium/hyper/"
rev = "2a19ab74ed69bc776da25544e98979c9fb6e1834"
optional = true
