[package]
name = "tendermint-rpc"
version = "0.1.0"
authors = ["Alexander Simmerl <a.simmerl@gmail.com>"]
edition = "2018"

[features]
default = []
client = [ "async-tungstenite", "futures", "http", "hyper", "tokio" ]

[dependencies]
bytes = "0.5"
getrandom = "0.1"
serde = { version = "1", features = [ "derive" ] }
serde_bytes = "0.11"
serde_json = "1"
tendermint = { version = "0.13.0", path = "../tendermint" }
thiserror = "1"
uuid = { version = "0.8", default-features = false }

async-tungstenite = { version="0.5", features = ["tokio-runtime"], optional = true }
futures = { version = "0.3", optional = true }
http = { version = "0.2", optional = true }
hyper = { version = "0.13", optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }
