version: 2.1

executors:
  cargo-executor:
    docker:
      - image: rust:1
    resource_class: large
  cargo-audit-executor:
    docker:
      - image: rust:1
    resource_class: small

commands:
  install_coverage_dependencies:
    steps:
      - run:
          name: Install grcov and zip
          command: |
            apt-get update
            apt-get install -y zip
            cargo install --force grcov
  print_version_info:
    steps:
      - run:
          name: Version information
          command: |
            rustup --version
            rustc --version
            cargo --version
  update_stable_toolchain:
    steps:
      - run:
          name: Update toolchain
          command: |
            test -z "stable" || echo "stable" >rust-toolchain
            rustup show active-toolchain
  update_nightly_toolchain:
    steps:
      - run:
          name: Update nightly toolchain
          command: |
            test -z "nightly" || echo "nightly" >rust-toolchain
            rustup show active-toolchain
  calculate_cargo_dependencies:
    steps:
      - run:
          name: Calculate dependencies
          command: test -e Cargo.lock || cargo generate-lockfile

jobs:
  # test-nightly-coverage:
  #   description: Collect and upload test coverage using the nighly toolchain
  #   executor: cargo-executor
  #   steps:
  #     - checkout
  #     - update_nightly_toolchain
  #     - print_version_info
  #     - install_coverage_dependencies
  #     - calculate_cargo_dependencies
  #     - run:
  #         name: Run tests with coverage env
  #         command: |
  #           export CARGO_INCREMENTAL=0
  #           export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
  #           cargo clean
  #           cargo test --all --verbose
  #     - run:
  #         name: Collect and upload test coverage
  #         command: |
  #           # Note: this currently only matches gc files in crates named *tendermint*.
  #           # This is something to keep in mind if we create crates that do not have tendermint in
  #           # their name.
  #           zip -0 ccov.zip `find . \( -name "*tendermint*.gc*" \) -print`
  #           grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
  #           bash <(curl -s https://codecov.io/bash) -f lcov.info
  #           rm -f lcov.info
  #           rm -f ccov.zip
