[package]
name = "tendermint-proto"
version = "0.19.0"
authors = ["Greg Szabo <greg@informal.systems>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/informalsystems/tendermint-rs/tree/master/proto"
readme     = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies", "database"]
keywords   = ["blockchain", "tendermint", "proto"]

description = """
    tendermint-proto is a the Rust implementation of the Tendermint proto structs.
    """

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost = { version = "0.7", default-features = false }
prost-types = { version = "0.7", default-features = false }
bytes = {version = "1.0", default-features = false }
anyhow = {version = "1.0", default-features = false }
displaydoc = {version = "0.2", default-features = false}
serde = { version = "1.0", default-features = false, features = ["derive"] }
subtle-encoding = { version = "0.5", default-features = false, features = ["alloc", "hex", "base64"] }
serde_bytes = { version = "0.11", default-features = false }
num-traits = { version = "0.2", default-features = false }
num-derive = "0.3"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
no-std-compat = { version = "0.4.1", features = [ "alloc" ] }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
    'bytes/std',
    'chrono/std',
    'prost/std',
    'prost-types/std',
    'anyhow/std',
    'displaydoc/std',
    'serde/std',
    'serde_bytes/std',
    'subtle-encoding/std',
    'num-traits/std',
    'no-std-compat/std',
]