[package]
name = "tendermint-testgen"
version = "0.17.0-rc1"
authors = ["Andrey Kuprianov <andrey@informal.systems>"]
edition = "2018"
publish = false

[dependencies]
tendermint = { version = "0.17.0-rc1", path = "../tendermint" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ed25519-dalek = "1"
gumdrop = "0.8.0"
simple-error = "0.2.1"
tempfile = "3.1.0"

[[bin]]
name = "tendermint-testgen"
path = "bin/tendermint-testgen.rs"
