name: Test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  # TODO(shonfeder): remove duplication once GitHub addresses one of these
  #  - https://github.community/t/support-for-yaml-anchors/16128/15
  #  - https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/13
  #  - https://github.community/t/using-matrix-variable-in-docker-image-name/17296
  tendermint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint
  tendermint-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-rpc
  tendermint-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-proto
  tendermint-light-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-light-client
  # From https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/continuous-integration.html#github-actions
  tendermint-light-client-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --headless --chrome ./light-client-js/
      - run: wasm-pack test --headless --firefox ./light-client-js/
  tendermint-light-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-light-node
  tendermint-testgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-testgen

  kvstore-integration-stable:
    runs-on: ubuntu-latest
    services:
      tendermint:
        image: informaldev/tendermint:0.34.0
        ports:
          - 26656:26656
          - 26657:26657
          - 26660:26660
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: --manifest-path tools/kvstore-test/Cargo.toml -- --nocapture
        env:
          RUST_LOG: debug

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0-alpha1'
          # TODO(thane): Remove package-specific parameter once https://github.com/informalsystems/tendermint-rs/issues/841 is resolved
          args: '--all-features --no-fail-fast --timeout 600 -p tendermint-abci,tendermint-light-client,tendermint-light-node,tendermint-proto,tendermint-rpc,tendermint,tendermint-testgen -- --test-threads 1'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cobertura.xml
